# Imports

In [11]:
## Importar las liberías que voy a usar en la calse

import matplotlib.pyplot as plt
import numpy as np

# Clase 1
## Ejercicio 1 y 2

In [48]:
## Ejercicio 1

a = np.array([[1,2],[3,4]])

# calcular norma o = numero de elemoentos diferentes a 0
# norma p sumatoria de x1_p
# norma infinito maximo valor de la matriz

def norm_0(m):
    n0 = np.sum(m != 0) 
    return n0

def norm_p(m, p): 
    xp = np.sum(np.positive(m**p)**(1/p))
    return xp

def norm_2(m): 
    xp = np.sum(np.abs(m)**2, axis=1)**(1/2)
    return xp

def norm_inf(m): 
    xinf = np.max(m, axis=1)
    return xinf

In [64]:
np.argsort(a) # ordena los numeros y arroja los indices correspondientes
def ej_2(m):
    N_2 = norm_2(m)
    N_2_S = np.argsort(N_2)
    return m[N_2_S]

ej_2(a)

b = np.array([[1,2,3,4],[5,6,7,8],[9,9,9,9]])
N_2 = norm_2(b)
N_2_S = np.argsort(b)



print(ej_2(b))

[[1 2 3 4]
 [5 6 7 8]
 [9 9 9 9]]


array([ 5.47722558, 13.19090596, 18.        ])

## Ejercicio 3

In [17]:
## Ejercicio 3

class Index(object):
    def __init__(self, ids):
        print('__init__')
        unique_ids = np.unique(ids)
        id2idx = np.ones(max(unique_ids) + 1, dtype=np.int64)*-1
        id2idx[unique_ids] = np.arange(unique_ids.size)
        self.id2idx = id2idx
        self.idx2id = unique_ids
    
    def get_idxs(self, ids):
        ids = self.id2idx[ids]
        return ids, ids != -1
    
    def get_ids(self, idxs):
        return self.idx2id[idxs]

## Ejercicio 4

In [80]:
### Ejercicio #4: precision, recall y accuracy
"""En clasificación contamos con dos arreglos, la “verdad” y la “predicción”. Cada elemento de los arreglos
pueden tomar dos valores, “True” (representado por 1) y “False” (representado por 0). Entonces podemos
definir 4 variables:
● True Positive (TP): la verdad es 1 y la producción es 1.
● True Negative (TN): la verdad es 0 y la predicción es 0.
● False Negative (FN): la verdad es 1 y la predicción es 0.
● False Positive (FP): la verdad es 0 y la producción es 1.
Se definen las siguientes métricas:
● Precision = TP / (TP + FP)
● Recall = TP / (TP + FN)
● Accuracy = (TP + TN) / (TP + TN + FP + FN)
Suponer que se tienen 2 arreglos:
truth = [1,1,0,1,1,1,0,0,0,1]
prediction = [1,1,1,1,0,0,1,1,0,0]
Calcular las 3 métricas con Numpy y operaciones vectorizadas."""

truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

class Metrics(BaseMetric):
    
    def __init__(self, truth, prediction):
        self.truth = truth
        self.prediction = prediction
    
    def get_precision(self):
        values_count = len(truth)
        true_positives = np.sum(np.logical_and([self.truth == 1], [self.prediction == 1]))
        false_positives = np.sum(np.logical_and([self.truth == 0], [self.prediction == 1]))
        true_negatives = np.sum(np.logical_and([self.truth == 0], [self.prediction == 0]))
        false_negatives = np.sum(np.logical_and([self.truth == 1], [self.prediction == 0]))
        Precision = true_positives / ( true_positives + false_positives)
        return Precision
    
    def get_accuracy(self):
        values_count = len(truth)
        true_positives = np.sum(np.logical_and([self.truth == 1], [self.prediction == 1]))
        false_positives = np.sum(np.logical_and([self.truth == 0], [self.prediction == 1]))
        true_negatives = np.sum(np.logical_and([self.truth == 0], [self.prediction == 0]))
        false_negatives = np.sum(np.logical_and([self.truth == 1], [self.prediction == 0]))
        Accuracy = (true_positives + true_negatives) / values_count
        return Accuracy
    
    def get_recall(self):
        values_count = len(truth)
        true_positives = np.sum(np.logical_and([self.truth == 1], [self.prediction == 1]))
        false_positives = np.sum(np.logical_and([self.truth == 0], [self.prediction == 1]))
        true_negatives = np.sum(np.logical_and([self.truth == 0], [self.prediction == 0]))
        false_negatives = np.sum(np.logical_and([self.truth == 1], [self.prediction == 0]))
        Recall = true_positives / (true_positives + false_negatives)
        return Recall
    

## Ejercicio 5

In [188]:
### Ejercicio #5: average query precision

"""En information retrieval o search engine, en general contamos con queries “q” y para cada “q” una lista de
documentos que son verdaderamente relevantes. Para evaluar search engine, es común utilizar la métrica
average query precision. Dado un search engine y una lista de queries “q” para evaluación, podemos obtener
los siguientes resultados:
q_id = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]
predicted_rank = [0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]
truth_relevance = [T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T ]
precision para q_id 1 = 2 / 4
precision para q_id 2 = 3 / 3
precision para q_id 3 = 0 / 5
precision para q_id 4 = 2 / 4
average query precision = ((2/4) + (3/3) + (0/5) + (2/4)) / 4
Calcular la métricas con Numpy y operaciones vectorizadas."""

T = True
F = False

q_id = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4])
predicted_rank = np.array([0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3])
truth_relevance = np.array([T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T ])

max_query = max(q_id)

# Modo List Comprehension

query_truth = [np.sum(truth_relevance[(q_id == i)]) for i in range(1,max_query+1)]
query_fetched = [len(truth_relevance[(q_id == i)]) for i in range(1,max_query+1)]
query_precision = np.divide(query_truth, query_fetched)
avg_q_precision = np.average(query_precision)


# Modo Vectorizado

# filtrar y contar cantidad de resultados relevantes por query 
truth_relevance_mask = (truth_relevance == T)
filtered_true_query_id = q_id[truth_relevance_mask]
filtered_true_relevance_count = np.bincount(filtered_true_query_id)

# generar la lista correcta de relevance counts
unique_query_ids = np.unique(q_id)
non_zero_count_idx = np.where(filtered_true_relevance_count > 0)
true_relevance_counts = np.zeros(max(unique_query_ids)+1)
true_relevance_counts[non_zero_count_idx] = filtered_true_relevance_count[non_zero_count_idx]

# obtener la el conteo sólo para queries existentes
true_relevance_counts_by_query = true_relevance_counts[unique_query_ids]

#get the count of fetched documents
fetched_documents_count = np.bincount(q_id)[unique_query_ids]

#precision
precision_by_query = true_relevance_counts_by_query / fetched_documents_count

print(np.mean(precision_by_query))
print(avg_q_precision)

0.5
0.5


## Ejercicio 6

In [20]:
"""Ejercicio #6: average query precision at K
En information retrieval o search engine, en general contamos con queries “q” y para cada “q” una lista de
documentos que son verdaderamente relevantes. Para evaluar search engine, es común utilizar la métrica
average query precision at K. Dado un search engine y una lista de queries “q” para evaluación, podemos
obtener los siguientes resultados:
k = 3
q_id = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]
predicted_rank = [0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]
truth_relevance = [T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T ]
precision para q_id 1 = 2 / 3
precision para q_id 2 = 3 / 3
precision para q_id 3 = 0 / 3
precision para q_id 4 = 1 / 3
average query precision at K = ((2/3) + (3/3) + (0/3) + (1/3)) / 4
Calcular la métricas con Numpy y operaciones vectorizadas."""
T = True
F = False

q_id = [1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4]
predicted_rank = [0, 1, 2, 3, 0, 1, 2, 0, 1, 2, 3, 4, 0, 1, 2, 3]
truth_relevance = [T, F, T, F, T, T, T, F, F, F, F, F, T, F, F, T ]
q_id = np.array(q_id)
predicted_rank = np.array(predicted_rank)
truth_relevance = np.array(truth_relevance)
k = 3

# generate masks for the true vales
truth_relevance_mask = truth_relevance == True
unique_ids = np.unique(q_id)
predicted_rank_K_mask = predicted_rank < k
truth_relevance_l_k_mask = np.logical_and(predicted_rank_K_mask, truth_relevance_mask)

# Filter relevant queries for bincount

relevant_filtered_queries = q_id[truth_relevance_l_k_mask]

# Bincunt! count the true values per query
relevant_count_query_ALL = np.bincount(relevant_filtered_queries)

relevant_count_query = relevant_count_query_ALL[unique_ids]

# Calculate query i precision!
query_precision = relevant_count_query / k

# Calculate avg. query precision

avg_query_precision = np.mean(query_precision)


## Ejercicio 7

In [7]:
"""Ejercicio #7: computar todas las métricas con __call__
En problemas de machine learning, es muy común que para cada predicción que obtenemos en nuestro
dataset de verificacion y evaluacion, almacenemos en arreglos de numpy array el resultado de dicha
predicción, junto con el valor verdadero y parámetros auxiliares (como el ranking de la predicción y el query
id).
Luego de obtener todas las predicciones, podemos utilizar la información almacenada en los arreglos de
numpy, para calcular todas las métricas que queremos medir en nuestro sistema.
Una buena práctica para implementar esto en Python, es crear clases que hereden de una clase Metric
“base” y que cada métrica implemente el método __call__.
Utilizar herencia, operador __call__, kwargs, para escribir un programa que permita calcular todas las
métricas de los ejercicios anteriores mediante un for. Cual es la ventaja de resolver el problema utilizando
estas herramientas?"""


truth = np.array([1,1,0,1,1,1,0,0,0,1])
prediction = np.array([1,1,1,1,0,0,1,1,0,0])

class BaseMetric:
    def __init__(self, truth, prediction):
        self.truth = truth
        self.prediction = prediction
        
        self.true_positives = np.sum(np.logical_and([truth == 1], [prediction == 1]))
        self.false_positives = np.sum(np.logical_and([truth == 0], [prediction == 1]))
        self.true_negatives = np.sum(np.logical_and([truth == 0], [prediction == 0]))
        self.false_negatives = np.sum(np.logical_and([truth == 1], [prediction == 0]))

class Precision(BaseMetric):
    
    def __call__(self):
        values_count = len(self.truth)
        Precision = self.true_positives / ( self.true_positives + self.false_positives)
        return Precision
    
class Accuracy(BaseMetric):
    def __call__(self):
        values_count = len(self.truth)
        Accuracy = (self.true_positives + self.true_negatives) / values_count
        return Accuracy
    
class Recall(BaseMetric):
    
    def __call__(self):
        values_count = len(self.truth)
        Recall = self.true_positives / (self.true_positives + self.false_negatives)
        return Recall
    

metrics = [BaseMetric(truth, prediction), Accuracy(truth, prediction), Recall(truth, prediction)]

for metric in metrics:
    print(metric())
    


0.5
0.4
0.5


## Ejercicio 8

In [175]:
""" Ejercicio #8: transformar un dataset a numpy estructurado con singleton
Descargar un dataset de ejemplo de la siguiente URL:
https://www.kaggle.com/rounakbanik/the-movies-dataset/data?select=ratings.csv
Crear la cuent en Kaggle, porque es un lugar de donde potencialmente vamos a descargar muchos recursos.
Crear un array estructurado en numpy que represente correctamente la estructura del dataset (“userId”,
“movieId”, “rating”, “timestamp”).
Crear una clase que permita:
OK- Crear la estructura de un structured numpy array para el dataset.
OK- Leer el csv, almacenar la información en el array estructurado.
OK Guardar el array estructurado en formato .pkl
OK Crear una instancia singleton del array estructurado (utilizando __new__ e __init__).
● Al crear la instancia, si se encuentra el .pkl cargar desde el pkl. Si el .pkl no está, comenzar por
transformar el .csv en .pkl y luego levantar la información.
● Encontrar una forma de optimizar la operación usando generators."""

import numpy as np
import pickle
import os

# Constants

CSV_PATH = "C:/Users/jota_/00_Especialización_IA/00_Recursos/01_DataSets/ratings-MINI.csv"
PICKLE_PATH = 'C:/Users/jota_/00_Especialización_IA/00_Recursos/03_Pickled/ratings-MINI.pickle'


# Create Numpy Structure

struct_array = np.array([], 
                        dtype=[('userId',np.int32), 
                               ('movieId',np.int32) ,
                               ('rating',np.float32),
                               ('timestamp', np.float32)])


# Crear singleton

class structured_array_import(object):
    instance = None
    
    def __new__(cls, struct_array, CSV_PATH, PICKLE_PATH):
        if structured_array_import.instance is None:
            print('__new__ object created')
            structured_array_import.instance = super(structured_array_import, cls).__new__(cls)
            return structured_array_import.instance
        else: 
            return structured_array_import.instance
                                                                
    
    def __init__(self, struct_array, CSV_PATH, PICKLE_PATH):
        self.struct_array = struct_array
        self.CSV_PATH = CSV_PATH
        self.PICKLE_PATH = PICKLE_PATH
        
    
    def check_pickle(self):
        if os.path.getsize(self.PICKLE_PATH) > 0:
            return True
        elif os.path.exists(self.PICKLE_PATH):
            print('the pickle file exists but is empty')
            return False
        else:
            print('there is no pickle file')
            return False
        
    def load_pickle(self):    
        with open(self.PICKLE_PATH, 'rb') as f:
                            full_array = pickle.load(f)
                            print('full array is', full_array)
                            return full_array
    
    
    def load_file(self):
        
        """ This function will check if the corresponding pickle file exists. Is if does exist, 
        it will load the file from PICKLE, if it does not, it will load it throught the csv and 
        later save it in a pickle. """
        
        
        full_array = self.struct_array
        # Read CSV
        
        if self.check_pickle() == False:
        
            with open(self.CSV_PATH, 'r') as file:
                c = 0

                # Read CSV

                for row in file:
                    c += 1
                    raw_row = np.array([row.strip('\n').split(',')])
                    row_ful = np.zeros([1],dtype=self.struct_array.dtype)

                    # Fill struct array with CSV info.. This will CRUSH!! It does not adapt
                    # to new array structures.. :(
                    try:
                        row_ful[0][0] = raw_row[0][0].astype(np.int32) 
                        row_ful[0][1] = raw_row[0][1].astype(np.int32)
                        row_ful[0][2] = raw_row[0][2].astype(np.float32)
                        row_ful[0][3] = raw_row[0][3].astype(np.int32)

                        full_array = np.hstack((full_array, row_ful))

                    except:    
                        print("Se omitió la fila {}".format(c))

            with open(PICKLE_PATH, 'wb') as f:
                pickle.dump(full_array, f)

            return full_array
        else:
            full_array = self.load_pickle()
            return full_array

    