In [50]:
import importlib
from Clase1_NLP import ValueFrequency, VfIdf, One_Hot_Enconding, cosine_similarity
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
corpus = np.array(['hola como estas', 'hola bien vos', 'el domingo hubo mucho sol', 'ser o no ser', 'yo quiero ser un pez'])

# Value Frequency

In [52]:
valuefrec = ValueFrequency()
valuefrec.fit(corpus)
valuefrec.transform()

array([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.],
       [0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 2., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
        1.]])

# One Hot Encoding

In [53]:
one_hot = One_Hot_Enconding()
one_hot.fit(corpus)
one_hot.transform()

array([[0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0.],
       [0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0.,
        1.]])

# TFIDF

In [54]:
vfidf = VfIdf()
vfidf.fit(corpus)
vf_idf = vfidf.transform()

# Cosine similarity

In [55]:
cf = cosine_similarity(vf_idf[0], vf_idf[2])
print(cf)

docs = vf_idf
n_docs = docs.shape[0]

cs_martix = np.zeros(shape=[n_docs, n_docs])

for i in range(n_docs):
    for j in range(n_docs):
        cs_martix[i,j]= cosine_similarity(doc1=docs[i], doc2=docs[j])
        
print(cs_martix)

0.0
[[1.         0.13946264 0.         0.         0.        ]
 [0.13946264 1.         0.         0.         0.        ]
 [0.         0.         1.         0.         0.        ]
 [0.         0.         0.         1.         0.17170034]
 [0.         0.         0.         0.17170034 1.        ]]
