# Matemática para inteligencia Artificial


### 2.4 Ejercicio
Halle los autovalores y autovectores de
$A = [1 2//2 1]$

y halle dos matrices distintas $P1, P2$ tales que $D = P_1^{−1} A ∗ P_1 = P_2^{−1}A∗P_2$, donde

D es una matriz diagonal.


$A = \begin{pmatrix} 1 & 2 \\ 2 & 1 \end{pmatrix}$

Primero debo hallar los autovalores. Para hallarlos realizo el cálculo: $det(A - \lambda I) = 0$.

El resultado de esa operación arroja $\lambda_1 = 3, E_1 = \begin{pmatrix} 1 \\ 1 \end{pmatrix}$. $\lambda_2 = -1, E_2 = \begin{pmatrix} 1 \\ -1 \end{pmatrix}$


Por cómo se construyeron los Autovectores,  sé que  $AE_1 = \lambda_1 E_1 y AE_2 = \lambda_2 E_2$ Puedo escribir esto mismo de la siguiente forma:

$A \begin{pmatrix} E_1 & E_2 \end{pmatrix} = \begin{pmatrix} \lambda_1 E_1 & \lambda_2 E_2 \end{pmatrix} 
=  \begin{pmatrix} E_1 &  E_2 \end{pmatrix}  \begin{pmatrix} \lambda_1 &  0 \\ 0 & \lambda_2 \end{pmatrix} $


$A \begin{pmatrix} E_1 & E_2 \end{pmatrix} =  
\begin{pmatrix} E_1 &  E_2 \end{pmatrix}  \begin{pmatrix} \lambda_1 &  0 \\ 0 & \lambda_2 \end{pmatrix} $

$\begin{pmatrix} E_1 & E_2 \end{pmatrix}^{-1} A \begin{pmatrix} E_1 & E_2 \end{pmatrix} =  
\begin{pmatrix} E_1 & E_2 \end{pmatrix}^{-1}\begin{pmatrix} E_1 &  E_2 \end{pmatrix}  \begin{pmatrix} \lambda_1 &  0 \\ 0 & \lambda_2 \end{pmatrix} $


$\begin{pmatrix} E_1 & E_2 \end{pmatrix}^{-1} A \begin{pmatrix} E_1 & E_2 \end{pmatrix} =  
\begin{pmatrix} \lambda_1 &  0 \\ 0 & \lambda_2 \end{pmatrix} $

Por lo tanto, las dos matrices P1, P2 serán:

$P_1 =  \begin{pmatrix} 1 &  1 \\ 1 & -1 \end{pmatrix} $, $D = \begin{pmatrix} 3 &  0 \\ 0 & -1 \end{pmatrix}$

De igual manera, puedo multiplicar los Autovectores por un escalar, lo que arrojará la matriz $P_2$ que mantendrá sus propiedades.

$P_2 =  \begin{pmatrix} 2 &  2 \\ 2 & -2 \end{pmatrix} $


### 2.5 Ejercicio
Halle los autovalores y autovectores de
A =

[1/3 −1/3
4/3 5/3] 

y explique por qu ́e no puede ser diagonalizada. Halle una matriz P tal que $P AP^{−1}$ =
λ 1
0 λ

para alg ́un valor de λ.

$A = \begin{pmatrix} 1/3 & -1/3 \\ 4/3 & 5/3 \end{pmatrix}$

Primero debo hallar los autovalores. Para hallarlos realizo el cálculo: $det(A - \lambda I) = 0$.

El resultado de esa operación arroja $\lambda_{1, 2} = 1$, $E_{1,2} = \begin{pmatrix} X \\ -2X \end{pmatrix} = X \begin{pmatrix} 1 \\ -2 \end{pmatrix}$.

Es requisito para que las matrices sean diagonalizables que se pueda formar una base del subespacio con los autovectores. En este caso, se observa que esto no es posible, pues el subespacio generado de la matriz está compuesto sólamente por los vectores gen{(1, -4)}.

El ejericio pide entonces encontrar una matriz P tal que $PAP^{-1} = \begin{pmatrix} \lambda & 1 \\ 0 & \lambda \end{pmatrix}$

$ P^{-1} = \begin{pmatrix} W_1 &  W_2 \end{pmatrix} $

$A \begin{pmatrix} W_1 & W_2 \end{pmatrix} = \begin{pmatrix} W_1 & W_2 \end{pmatrix} \begin{pmatrix} \lambda &  1 \\ 0 & \lambda \end{pmatrix}$

$ A W_1 = \lambda W_1 ; A W_2 = W_1 + \lambda W_2$

1) $(A - \lambda I)W_1 = 0 $ 

2) $(A - \lambda I) W_2 = W_1$

W_1 siendo el autovector de la matriz, puedo generar la siguiente igualdad:

$(A- \lambda I)(A-\lambda I)W_2 = 0$

Puedo afirmar que esto se cumple, pues $(A-\lambda I )W_2 = W_1$ y $(A-\lambda I )W_1 = 0$.

Esto representa la forma de jordan de la matriz.

$(A- \lambda I)^2W_2 = 0$

De esta manera, $W_1 = \begin{pmatrix} 1 \\ -2 \end{pmatrix}$ y $W_2 = \begin{pmatrix} -3 \\ 3 \end{pmatrix}$.



In [31]:
import numpy as np

print('W2: \n', np.array([[-3],[3]])) 
print('W1: \n',(np.array([[1/3, -1/3],[4/3, 5/3]]) - np.eye(2)) @ np.array([[-3],[3]]))
print('Multiplicación (A - lam I)**2 W2: \n', (np.array([[1/3, -1/3],[4/3, 5/3]]) - np.eye(2)) @ (np.array([[1/3, -1/3],[4/3, 5/3]]) - np.eye(2)) @ np.array([[-3],[3]]))

W2: 
 [[-3]
 [ 3]]
W1: 
 [[ 1.]
 [-2.]]
Multiplicación (A - lam I)**2 W2: 
 [[-3.33066907e-16]
 [ 3.33066907e-16]]



### 2.6 Ejercicio

Sean S un subespacio de $C^n$ y P ∈ C^{n×n} una matriz tal que P x = proxS x. ¿Es diagonalizable

esta matriz? ¿Los autovalores dependen del producto interno? ¿y los autovectores?


Para saber si la matriz P es diagonalizable, debo encontrar que todos sus autovalores sean mayores a 0. Primero planteo que la la transformación de P sobre x.

Puedo representar el espacio vectorial V como: $V = S \bigoplus S^\bot $. Consecuentemente, cada vector X se podrá descomponer en una componente dento de S y otra dentro de S ortogonal: $X = [X - proy_s X] + proy_s X$

La descomposición creada cumplirá: $[X - proy_s X] \in S^\bot ; proy_s X \in S $

$<X - proy_{s^\bot}X , proy_{s}X> =? 0 $

$<proy_{s^\bot}X , proy_{s}X> = 0 $

$<x - proy_{s}X - proy_{s^\bot}X,  proy_{s}X> = 0 $

Entonces puedo afirmar que: 

$<x - proy_{s^\bot}X , proy_{s}X> = 0 $


Por otro lado, tengo que:
${V_1, V_2,...,  V_r, V_{r+1}, ..., V_n} base de C^n$

Entonces, P estará construida por una C.L. de los elementos de la Base descripta desde V1 ... Vr.

$P.V1 = Proy_s V_1 = V_1$

Entonces V1 por definición será un autovector de S con autovalor 1.

Por inducción puedo inferir que enonces tendré Vr autovectores L.I. asociados al autovalor 1.

Para el resto de los elementos de la base, asociados a S ortogonal, los autovalores serán 0, pues la proyección estará en el nucleo.

Los autovectores cambiarán en función del subespacio, pero los autovalores se mantendrán inmutados.

Si uno cambia el producto interno, cambia la base de S ortogonal, dado que la definición de ortogonal cambiará con el P.i. Sin embargo, S queda inmutado.