# Matemática para inteligencia Artificial

## Ejercicios clase 3

### Ejercicio 3

1. A = $
\begin{vmatrix}
1 & 2\\
3 & 4\\
5 & 6\\
\end{vmatrix}
$

2. B = $
\begin{vmatrix}
1 & 2\\
1 & 2\\
\end{vmatrix}$

Según lo deducido del método de ortogonalización de Graham Schmidt:

$$v1 = g1$$
$$v2 = \frac{<v2,g1>}{||g1||^2} + g2  $$

Que matricialmente se representa cómo:

$$ Q =
\begin{vmatrix}
\frac{g1}{||g1||}, \frac{g2}{||g2||}
\end{vmatrix}$$


$$ R =
\begin{vmatrix}
||g1|| & \frac{<v2,g1>}{||g1||}\\
0 & ||g2|| \\
\end{vmatrix}$$



In [2]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])

B = np.array([[1, 2], [1, 2]])

In [120]:
v1 = A.T[0].reshape(3,1)
v2 = A.T[1].reshape(3,1)

#Ortogonalización de vectores
g1 = v1
g2 = v2 - np.dot(v2.T, v1)/np.dot(v1.T ,v1)*  v1

#prueba de ortogonalidad
print(np.dot(g2.T, g1))

#cálculo de normas de vectores ortogonales
g1_norm = (np.dot(g1.T,g1)**0.5)[0][0]
g2_norm = (np.dot(g2.T,g2)**0.5)[0][0]

#normalización de vecores ortogonales
g1_unit = g1 / g1_norm
g2_unit = g2 / g2_norm

#armado de matriz Q
Q = np.hstack((g1_unit, g2_unit))

# Armado de matriz R

R = np.array([[g1_norm, np.dot(v2.T, g1)[0][0]/g1_norm ],
              [0 , g2_norm]])

np.matmul(Q, R)

# Creación de función que realiza la descomposición QR para hacer ej b

def qr_descomposition(A):
    
    filas = A.shape[0]
    columnas = A.shape[1]
    
    matriz_ortogonal = np.zeros(shape=[filas,columnas])
    matriz_ortonormal = np.zeros(shape=[filas,columnas])
    R_matrix = np.zeros(shape=[columnas, columnas])

    for i in range(columnas):
        matriz_ortogonal[:,i] = A[:,i]
        g_j = 0

        for j in range(i):
            g_j = matriz_ortogonal[:,j]
            v_projection_gj = np.dot(A[:,i].T, g_j)/ np.dot(g_j.T ,g_j)
            matriz_ortogonal[:,i] = matriz_ortogonal[:,i] - v_projection_gj * g_j
            R_matrix[i,j] = v_projection_gj *  np.dot(g_j.T ,g_j)**0.5

        R_matrix[i,i] = np.dot(matriz_ortogonal[:,i], matriz_ortogonal[:,i])**0.5

        matriz_ortonormal[:,i] = matriz_ortogonal[:,i] / R_matrix[i,i]
    
    return matriz_ortonormal, R_matrix.T

Qb, Rb = qr_descomposition(B)

# como la proyeccion de V2 sobre V1 cae totalmente dentro de V1,la matriz QR tendrá una dimensión menos, pues elimina ese vector

[[8.8817842e-16]]


C:\Users\jota_\anaconda\lib\site-packages\ipykernel_launcher.py:52: RuntimeWarning: invalid value encountered in true_divide


In [127]:
Qb

array([[0.70710678,        nan],
       [0.70710678,        nan]])

In [130]:
A = B
filas = A.shape[0]
columnas = A.shape[1]

matriz_ortogonal = np.zeros(shape=[filas,columnas])
matriz_ortonormal = np.zeros(shape=[filas,columnas])
R_matrix = np.zeros(shape=[columnas, columnas])

for i in range(columnas):
    matriz_ortogonal[:,i] = A[:,i]
    g_j = 0
    
    for j in range(i):
        print(matriz_ortogonal[:,i])
        g_j = matriz_ortogonal[:,j]
        v_projection_gj = np.dot(A[:,i].T, g_j)/ np.dot(g_j.T ,g_j)
        matriz_ortogonal[:,i] = matriz_ortogonal[:,i] - v_projection_gj * g_j
        R_matrix[i,j] = v_projection_gj *  np.dot(g_j.T ,g_j)**0.5
        print(matriz_ortogonal[:,i])
    R_matrix[i,i] = np.dot(matriz_ortogonal[:,i], matriz_ortogonal[:,i])**0.5
        
    matriz_ortonormal[:,i] = matriz_ortogonal[:,i] / R_matrix[i,i]

np.matmul(matriz_ortonormal, R_matrix.T)

[2. 2.]
[0. 0.]


C:\Users\jota_\anaconda\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: invalid value encountered in true_divide


array([[nan, nan],
       [nan, nan]])

array([[5.91607978, 7.43735744],
       [0.        , 0.82807867]])